spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.224.53.83:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 10.224.53.83
    port: 6379
server:
  context-path: /sell
logging:
  level:
    com.imooc.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml